apiVersion: apps/v1
kind: Deployment
metadata:
 name: producer_rest
spec:
 selector:
   matchLabels:
     app: producer_rest
 template:
   metadata:
     labels:
       app: producer_rest
   spec:
     containers:
     - name: producer_rest
       image: sumyatphyoe/producer_rest
       ports:
       - containerPort: 8080
 
---
apiVersion: v1
kind: Service
metadata:
 name: producer_rest
spec:
 type: NodePort
 selector:
   app: producer_rest
 ports:
 - port: 81
   targetPort: 8080
   nodePort: 31500